### ISSUE TITLE
Total Number of Reads Did Not Match

### ISSUE THREAD

**Issue by fungshui** [VDBWRAIR/ngs_mapper#271]
Run setting: default configuration running 1 sample against 2 different references (total number of reads did not match). For troubleshooting purposes, ngs_mapper was run twice, 1 sample against 1 reference.

Since it is the same sample, the total number of reads from both results should be the same. The runs produced different total reads:
14999_c1 has 361350 reads
14999_c2 has 360988 reads
Only difference should be the number of mapped and unmapped reads.

Attached below are the reference files, qualdepth.pdf files, and json files:

[14999_references.zip](https://github.com/VDBWRAIR/ngs_mapper/files/1394790/14999_references.zip)
[14999_c1_stats.zip](https://github.com/VDBWRAIR/ngs_mapper/files/1394796/14999_c1_stats.zip)
[14999_c2_stats.zip](https://github.com/VDBWRAIR/ngs_mapper/files/1394798/14999_c2_stats.zip)

**Comment by averagehat** [comment]
Copied from gitter:

The difference is more or less consistent with the output of bwa, which showed a similar discrepancy of about 460

it looks like c1 reported more reads mapped/unmapped than it had as actual input, which can happen due to chimeric alignment
I guess the lesson here is that unmapped+mapped =/= total reads input, and if for some reason you want to know how many reads were input to bwa, you should look in the trimmed_reads directory
http://seqanswers.com/forums/showthread.php?t=32708
